library(dplyr)
X_test <- read.table('test//X_test.txt')
X_train <- read.table('train//X_train.txt')
X_data <- rbind(X_test, X_train)
features <- read.table('features.txt')
colnames(X_data) <- features[,2]
feat <- as.vector(features[c(1:6,41:46,81:86,121:126,161:166,201:202,214:215,227:228,240:241,253:254,266:271,345:350,424:429,503:504,516:517,529:530,542:543),2])
X_select <- X_data[feat]
sub_test <- read.table('test//subject_test.txt')
sub_train <- read.table('train//subject_train.txt')
sub <- rbind(sub_test, sub_train)
names(sub) <- 'subject'
X_select <- cbind(sub, X_select)
Y_test <- read.table('test//y_test.txt')
Y_train <- read.table('train//y_train.txt')
Y_data <- rbind(Y_test, Y_train)
names(Y_data) <- 'activity_index'
data <- cbind(Y_data, X_select)
activity <- read.table('activity_labels.txt')
names(activity) <- c('activity_index', 'activity')
data_act <- merge(activity, data)
data_act <- select(data_act, 2:68)
names(data_act) <- sub('\\()', '', names(data_act))
datamelt <- melt(data_act, id = c('activity', 'subject'), measure.vars = names(data_act)[3:67])
breakdown <- dcast(datamelt, activity + subject ~ variable,mean)
